float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorSingle
    disabled: false
    docker_tag: ann-benchmarks-pgvectorsingle
    module: ann_benchmarks.algorithms.pgvector_single
    name: pgvector_ivfflat_single
    run_groups:
      single:
        arg_groups: [{batch_size: 5000, index_type: ivfflat, version: Origin}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
        # query_args: [[1]]
